### ISSUE TITLE
{Initial Feature: Homepage} 【Main-Issue】 Design the Main/Hero Section

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#111]
### Task: Design the Main/Hero Section

**Description:**
We need to design the **Main/Hero Section** for the homepage of the campus resource and event management web application. This section will serve as the focal point and should be visually engaging, containing both imagery and key text that reflects the purpose of the platform.

#### **Requirements:**
- [x] #121
  - Include a high-quality hero image or graphic that aligns with the website theme.
  - Ensure the image is responsive and scales properly across all devices (desktop, tablet, mobile).
  - The image should blend well with the overall color scheme of the page.

- [ ] #122
  - Include the main headline that highlights the purpose of the platform (e.g., "Discover Events and Resources Easily").
  - Add a brief supporting subheading that explains the value proposition (e.g., "Manage your campus life effortlessly with our all-in-one platform").
  - Ensure that the text is legible, responsive, and styled to fit the design.
  - Include a call-to-action button (e.g., "Get Started" or "Explore Now").

#### **Acceptance Criteria:**
- A responsive and visually appealing hero image is added to the section, and it scales correctly across all devices.
- The headline, subheading, and call-to-action button are added with proper styling, spacing, and alignment.
- The text is clear, legible, and fits well with the overall design of the hero section.
- The section is fully responsive and performs well on various screen sizes and devices.
- The images and text blend harmoniously with the color scheme and overall design language of the website.

#### **Design Reference:**
- Figma File: [Eventero Design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?m=auto&t=WXZ03fz7DcJOl0ly-6)
- Figma reference picture: ![Image](https://github.com/user-attachments/assets/54022bf8-5e19-4e4a-87e2-19948852eb45)

#### **Documentation Reference:**
- Ensure commits follow the documentation guidelines: [Homepage doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7B93FC3995-80D4-42B5-BC60-4A9191E948C1%7D&file=Initial%20Feature%20-%20Homepage.docx&action=default&mobileredirect=true)
- Update any helper components in the: [Component Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB4E17698-6B3A-431E-BE28-33D16902D251%7D&file=Component%20Reference.docx&action=default&mobileredirect=true)
- Verify the feature integration: [Feature Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BBC785AF0-39F4-415F-A9E9-09297256B95E%7D&file=Feature%20Reference.docx&action=default&mobileredirect=true)

**Comment by AlexisSantiago21** [comment]
I designed the Main/Hero Section for the homepage of the campus resource and event management web application. This section includes a high-quality hero image that scales across all devices, a catchy headline that highlights the platform's purpose, a subheading that reinforces its value, and a call-to-action (CTA) button to encourage user interaction. I ensured that all elements are responsive, legible, and seamlessly integrate with the site's color scheme and overall design.
