### ISSUE TITLE
{Initial Feature: Homepage} 【Sub-Issue】Add images to the Main/Hero Section.

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#121]
**Description:**  
This issue is a continuation of the work discussed in **Issue #111**, and involves designing the **Main/Hero Section** for the homepage of the campus resource and event management web application. This section should be visually engaging and contain both imagery and key text that reflects the platform's purpose. The design should adhere to the Figma reference linked below.

#### **Acceptance Criteria:**
- A responsive and visually appealing hero image is added to the section, scaling correctly across all devices.
- The headline, subheading, and call-to-action button are added with proper styling, spacing, and alignment.
- The text is clear, legible, and fits well with the overall design of the hero section.
- The section is fully responsive and performs well on various screen sizes and devices.
- The images and text blend harmoniously with the color scheme and overall design language of the website.

#### **Design Reference:**
- Figma File: [Eventero Design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?m=auto&t=WXZ03fz7DcJOl0ly-6)

#### **Documentation Reference:**
- Ensure your commits are documented: [Homepage doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7B93FC3995-80D4-42B5-BC60-4A9191E948C1%7D&file=Initial%20Feature%20-%20Homepage.docx&action=default&mobileredirect=true)
- Update any helper components in the: [Component Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB4E17698-6B3A-431E-BE28-33D16902D251%7D&file=Component%20Reference.docx&action=default)
- Verify the feature integration: [Feature Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BBC785AF0-39F4-415F-A9E9-09297256B95E%7D&file=Feature%20Reference.docx&action=default)

**Comment by AlexisSantiago21** [comment]
done @arianrodz21  @AlexandraFuentes
