### ISSUE TITLE
{Initial Feature: Calendar}【Sub-Issue】Adding functionality to the calendar view buttons in the ribbon

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#136]
_Overview:_

> We’re enhancing the Calendar View functionality in the application! This feature will bring the calendar navigation to life by enabling the buttons in the ribbon to switch between different views. When a user clicks on the "Day" button, the calendar will display events specifically for October 28. This is a step towards making the calendar more interactive and user-friendly.

Objective:

> The goal is to implement a seamless calendar navigation experience where users can easily switch between day, week, and month views. The first implementation will involve displaying events for October 28 when the "Day" button is clicked, setting the foundation for future enhancements.

Tasks:
Frontend Development:
  

> Implement the functionality to switch the calendar view to "Day" when the "Day" button in the ribbon is clicked.
>   Ensure that clicking the "Day" button displays events specifically for October 28.
>   Integrate this functionality with the existing calendar component.

Example Scenario:

> Clicking on the "Day" button in the calendar ribbon will show a list of events for October 28, providing users with a detailed view of that day's schedule.

Main Issue :  #134

**Comment by cseba11** [comment]
@Adrianortiz-PR @AlexandraFuentes sub-issue #136 done.
