### ISSUE TITLE
{Initial Feature: Calendar}【Sub-Issue】Adding functionality to the Create Event button and creating the CreateEventModal

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#137]
**_Overview:_**

> We're adding the ability to create events on the CalendarPage. This task involves setting up a modal for event creation that appears when the "Create Event" button is clicked in the ribbon. The goal is to lay the groundwork for the event creation process by displaying an empty modal.

_**Objective:**_

> The aim is to implement a basic event creation modal that appears in the center of the screen with a semi-transparent backdrop when the "Create Event" button is clicked. The modal will provide a foundation for future enhancements to the event creation process.

_**Tasks:**_

> - Create a component for the event creation modal with a fixed position in the center of the screen.
> - Add a semi-transparent backdrop behind the modal.
> - Ensure the modal appears when the button is clicked and disappears when the backdrop is clicked.
> - Style the modal with a white background and set the backdrop with a slight opacity.

**_Example Scenario:_**

> Clicking the "Create Event" button shows an empty modal in the center of the screen with a darkened backdrop.

Main Issue : #134

**Comment by cseba11** [comment]
@Adrianortiz-PR @AlexandraFuentes final sub-issue #137 done and main feature #134 completed.
