### ISSUE TITLE
{Initial Feature: Calendar}【Main-Issue】 Add Event Section

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#146]
**Description:** Create The Add Event Section component for the Calendar page as shown in the image below.
![Image](https://github.com/user-attachments/assets/d47759f7-0e58-45d1-9392-7230c191fce7)

**Requirements:**

- [x] #219
  - Create the event block on the leftside of the page

- [x] #147
  - Create the button show at the top of the design for adding events
  - Hovering the button turns it green.

- [x] #149
  - Create the button show at the top of the design for adding events
  - The text that says "Calendar" will not be added to the component.
  - The text that says "My events" and "other" are checkboxes. When they are checked, the dot is green, otherwise, it is grey.
  -When one is checked, the other is automatically unchecked. By default, "My events" will be checked.
  - Checking these inputs will change a variable in the CalendarPage that will be binded to this component.

**Acceptance Criteria:**
- Clicking the Add Event button opens a modal to create a new event.
- Clicking on the modals backdrop closes it
- Clicking on "My Events" or clicking on "Other" makes the clicked one green and the other one fray (refer to the design image above).
- Switching between them changes a variable in the CalendarPage component which is binded to this component.

**Comment by GabyMarr** [comment]
Completed all Sub Issues for Main Issue adhereing to acceptance criteria. @Adrianortiz-PR
