### ISSUE TITLE
{Initial Feature: Calendar}【Sub-Issue】 Event Filters

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#149]
Description:
This issue is a continuation of the work discussed in Issue https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/issues/146, and involves implementing a filters for the **My Events** button and **Other** on the event section. The filter accurately display which button is selected and deactives when the other button is pressed.

Acceptance Criteria:
The buttons and filters are styled appropriately and integrates well with the website's overall design.
The button and filters appears at all times during the viewing of the calendar page.
The functionality is tested across multiple devices and browsers to ensure responsiveness and performance.

Design Reference:
Figma File: [Eventero Design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?m=auto&t=WXZ03fz7DcJOl0ly-6)

**Comment by JeanSanchezFelix** [comment]
Duplicate Issue, please fix

**Comment by GabyMarr** [comment]
@Adrianortiz-PR Finished this Sub Issue
