### ISSUE TITLE
Student Major Selection for the tags

### ISSUE THREAD

**Issue by AlexandraFuentes** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#154]
### Discussed in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **EdzelOrtiz** September 20, 2024</sup>
Description:
After the Webpage Skeleton and the Faculty Selection has been created. Develop the different majors that are inside for each of the Faculties within them.

Requisites:
Stage 1:
- After the user selects their Faculty, there will be another set of tags that has all the majors inside the Faculty.

Engineering Majors:
- Chemical Engineering
- Civil Engineering
- Computer Engineering
- Computer Science and Engineering
- Electrical Engineering
- Industrial Engineering
- Mechanical Engineering
- Software Engineering
- Surveying and Topography

Business Administration Majors:
- Accounting
- Finance
- Human Resources Management
- Marketing
- Operations Management
- Marketing
- Operations Management
- Computerized Information Systems
- Office Administration

Arts and Sciences Majors:
- Comparative Literature
- Economics
- English
- History
- French Language and Literature
- Hispanic Studies
- Philosophy
- Physical Education - Teaching
- Physical Education - Physical Education - Training and Officiating
- Visual Arts
- Political Science
- Psychology
- Social Sciences
- Sociology
- Art Theory
- Biology
- Industrial Biotechnology
- Chemistry
- Geology
- Mathematics - Pure Mathematics
- Mathematics - Computer Science
- Mathematics Education
- Nursing
- Physics
- Physical Sciences

Agricultural Sciences Majors:
- Agricultural Sciences (General)
- Agronomy
- Agricultural Economics
- Food Science
- Horticulture
- Animal Science
- Crop Protection
- Agribusiness
- Agricultural Education
- Agricultural Extension
- Soil Science
- Agricultural and Environmental Systems
- Pre-Veterinary (Non-Degree Program)

Prerequisites:
- Resources:
     - Figma Design for the Tags Organization
     - Repositorie

Roles and Responsibilities:
- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

@EdzelOrtiz </div>

**Comment by Kiarancole** [comment]
Issue completed and visible in Faculty_Major_Buttons branch, will open PR for merging when associations are finished. @Adrianortiz-PR @AlexandraFuentes @EdzelOrtiz
