### ISSUE TITLE
Select Faculty as a Tag

### ISSUE THREAD

**Issue by AlexandraFuentes** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#156]
### Discussed in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **EdzelOrtiz** September 20, 2024</sup>
Description:
After creating the webpage skeleton. Develop the buttons for the Faculties that can be selected by the user using HTML and CSS.

Requisites:
Stage 1:
- Faculty Selection:
     - Create a section where users can select from the available faculties.
- There are 4 Faculties:
          - Engineering
          - Business Administration
          - Agricultural Sciences
          - Arts and Sciences
- Faculties will be displayed as buttons allowing users to select one.

Potential Challenges:
- Ensuring the design aligns with the Figma mockup in terms of spacing, colors, and fonts.

Prerequisites:
- Resources:
     - Figma Design for the Tags Organization
     - Repositorie

Roles and Responsibilities:
- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

@EdzelOrtiz </div>

**Comment by Kiarancole** [comment]
Issue was completed and merged with PR #234, along web skeleton. @Adrianortiz-PR @AlexandraFuentes @EdzelOrtiz
