### ISSUE TITLE
Webpage Skeleton for the Tags Organization

### ISSUE THREAD

**Issue by AlexandraFuentes** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#157]
### Discussed in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **EdzelOrtiz** September 20, 2024</sup>
@EdzelOrtiz 

Description:
Develop a webpage skeleton for the Tags using html and css in which it will follow the Figma design already implemented.

Requisites:
Stage 1
- Header Section:
     - A header with a title, indicating the purpose of the page.
     - Follows the design principles outlined in the Figma file.
     - Create Headers for the title, Faculties, Majors, and Associations
- Hyperlink to the webpage
     - Add a hyperlink on the homepage that directs users to the tag-based selection page.  

Potential Challenges:
Ensuring the design aligns with the Figma mockup in terms of spacing, colors, and fonts.
Making sure that the transitions between faculty, major, and association selections are smooth and intuitive.
Dynamically filtering majors and associations based on the user’s previous selection.

Development Steps:
HTML Structure:

Create a simple HTML document with sections for the header, faculty, majors, and associations.
Each section should have its own div or section tag, allowing future content or design elements to be easily added.
CSS Styling:

Basic styling for the header, selection sections (faculty, majors, associations), and overall page layout.
Focus on making the page visually aligned with the Figma design, ensuring responsive behavior across devices.
Hyperlink Integration:

Ensure the homepage has a hyperlink that connects to this tag-based page.
This link should be easy to find, labeled appropriately, and functional across the site.

Prerequisites:
- Resources:
     - Figma Design for the Tags Organization
     - Repositorie

Roles and Responsibilities:
- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.</div>

**Comment by Kiarancole** [comment]
Completed in linked branch. @EdzelOrtiz @AlexandraFuentes @Adrianortiz-PR
