### ISSUE TITLE
Creating Universal Associations Tags

### ISSUE THREAD

**Issue by AlexandraFuentes** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#160]
### Discussed in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/151

<div type='discussions-op-text'>

<sup>Originally posted by **EdzelOrtiz** September 26, 2024</sup>
Description: Create tags for the different Associations that exists officially within the University that allow members without any faculty or majors requirement.

Requisites:
Stage 1:
- After the user selects their Faculty, and Major, there will be another set of tags that has all the universal Official Associations from the University.

- Using the link provided by the research, [UPRM Organizations](https://www.uprm.edu/cms/index.php?a=file&fid=20375)

Prerequisites:
- Resources:
     - Figma Design for the Tags Organization
     - Repository

Roles and Responsibilities:
- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.</div>

**Comment by kevin-d-lopez** [comment]
Completed in "Faculty_Mayor_Buttons" commits @AlexandraFuentes @EdzelOrtiz

**Comment by AlexandraFuentes** [comment]
Please complete a PR before closing

**Comment by kevin-d-lopez** [comment]
Completed in pull request #297  @AlexandraFuentes @EdzelOrtiz
