### ISSUE TITLE
Identify Universal Associations for the Creation of the Tags

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#179]
Discussed in #177 

<sup>Originally posted by **EdzelOrtiz** October1, 2024</sup>

Description: Organize the Universal Associations that do not require for the member to be in a specific, Faculty or Major. The user can be a member of these associations with no limitations, the only limitation being that is a member of the University.

Requisites:
- Create a list of the Universal Associations the user can join with the only requirement being that the user is a member of the University

Prerequisites:
- Have the Faculties, majors tags done before starting
- Resources:
     - Figma Design for the Tags Organization
     - Repository

Roles and Responsibilities:

- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

**Comment by EdzelOrtiz** [comment]
Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by ggonza28** [comment]
Issue #179 done @Adrianortiz-PR @AlexandraFuentes
