### ISSUE TITLE
Categorize Associations with the Majors in Agricultural Sciences Faculty

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#180]
Discussed in #176 
<sup>Originally posted by **EdzelOrtiz** October 1, 2024</sup>

Description: Before developing the different tags for the associations, organize each organization in different lists to the different majors that the Association is looking for in members.
In this case, create different lists for the distinct majors within Agricultural Sciences Faculty and inside those lists, add the different associations that look for that specific major.

Requisites:
- Create different lists with the different majors inside the Agricultural Sciences Faculty with the associations that look for that specific major.

Prerequisites:
- Have the Faculties, majors tags done before starting
- Resources:
     - Figma Design for the Tags Organization
     - Repository

Roles and Responsibilities:

- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

**Comment by EdzelOrtiz** [comment]
Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by ggonza28** [comment]
Issue #180 completed @Adrianortiz-PR @AlexandraFuentes
