### ISSUE TITLE
Categorize Associations with the Majors in Arts and Sciences Faculty

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#181]
Discussed in #175 
<sup>Originally posted by **EdzelOrtiz** October 1, 2024</sup>

Description: Before developing the different tags for the associations, organize each organization in different lists to the different majors that the Association is looking for in members.
In this case, create different lists for the distinct majors within Arts and Sciences Faculty and inside those lists, add the different associations that look for that specific major.

Requisites:
- Create different lists with the different majors inside the Arts and Sciences Faculty with the associations that look for that specific major.

Prerequisites:
- Have the Faculties, majors tags done before starting
- Resources:
     - Figma Design for the Tags Organization
     - Repository

Roles and Responsibilities:

- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by EdzelOrtiz** [comment]
Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by AngelUPR** [comment]
@Adrianortiz-PR @AlexandraFuentes I have completed this issue

Here is the doc containing all the list of the majors and their organizations:
https://docs.google.com/document/d/11n2MDwXWgJA0QoO1pLQf5iMlGiY6Wz65mTNzuhHsv04/edit?tab=t.0
