### ISSUE TITLE
Categorize Associations with the Majors in Engineering Faculty

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#182]
Discussed in #174
<sup>Originally posted by **EdzelOrtiz** October 1, 2024</sup>

Description: Before developing the different tags for the associations, organize each organization in different lists to the different majors that the Association is looking for in members.
In this case, create different lists for the distinct majors within Engineering Faculty and inside those lists, add the different associations that look for that specific major.

Requisites:
- Create different lists with the different majors inside the Engineering Faculty with the associations that look for that specific major.

Prerequisites:
- Have the Faculties, majors tags done before starting
- Resources:
     - Figma Design for the Tags Organization
     - Repository

Roles and Responsibilities:

- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.

Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by EdzelOrtiz** [comment]
Use this link that has all the Official Organizations within the University
https://www.uprm.edu/cms/index.php?a=file&fid=20375

**Comment by ggonza28** [comment]
**Engineering Sciences and Materials**
Material Advantage UPRM Chapter
Email: material.uprm@gmail.com
ID: 195

American Nuclear Society University of Puerto Rico Mayaguez Student Section (ANS UPRM)
Email: ansuprm@gmail.com
ID: 359

Spartech Eco-Marathon (Supermileage)
Email: spartech.uprm@gmail.com
ID: 373

UPRM Moonbuggy Engineering Team
Email: moonbuggy.design@gmail.com
ID: 153

Tau Beta Pi (TBP)
Email: taubetapi.pra@gmail.com
ID: 135

**Chemical Engineering**
American Institute of Chemical Engineers (AIChE)
Email: aiche.inqu@gmail.com
ID: 2

Asociación Latinoamericana de Estudiantes de Ingeniería Química y Carreras Afines (ALEIQ)
Email: puertoricoaleiq@gmail.com
ID: 411

Pharmaceutical Engineering Student Society (PESS)
Email: pess@uprm.edu
ID: 369

Cokí Racing Team
Email: cokiracingteam@uprm.edu
ID: 334

Loxodon-1
Email: loxodon1.admissions@gmail.com
ID: 399

**Civil Engineering**
American Society of Civil Engineers (ASCE)
Email: asceuprm@gmail.com
ID: 3

Asociación General de Contratistas, Capítulo Universitario de Mayagüez (AGC UPRM)
Email: uprm.agc@gmail.com
ID: 7

4. Mechanical Engineering
Society of Automotive Engineers (SAE)
Email: sae@uprm.edu
ID: 52

American Society of Mechanical Engineers (ASME)
Email: asme@uprm.edu
ID: 129

UPRM Aero Design
Email: aerodesign.uprm@gmail.com
ID: 250

RUM Racing Baja (RB)
Email: baja.uprm@gmail.com
ID: 318

Spartech Eco-Marathon (Supermileage)
Email: spartech.uprm@gmail.com
ID: 373

Human Powered Vehicle Challenge (HPVC)
Email: hpvcuprm@gmail.com
ID: 258

5. Electrical and Computer Engineering
IEEE Robotics & Automation Society (IEEE RAS)
Email: ras.uprm@gmail.com
ID: 127

Institute of Electrical and Electronics Engineers (IEEE)
Email: ieee@uprm.edu
ID: 113

IEEE Women in Engineering (IEEE-WIE)
Email: wie@uprm.edu
ID: 111

IEEE Power and Energy Society UPRM (IEEE PES UPRM)
Email: pes.upr@gmail.com
ID: 59

IEEE Eta Kappa Nu - Cápitulo Lambda Tau (HKN)
Email: hkn@uprm.edu
ID: 112

Circuits and Systems Society (IEEE-CAS)
Email: cas@uprm.edu
ID: 56

UPRM Roboboat Team
Email: roboboat.uprm@gmail.com
ID: 332

AON Robotics
Email: vex.crome@gmail.com
ID: 421

Space Architectures and Revolutionary Concepts (SPARC)
Email: sparcuprm@gmail.com
ID: 396

**Industrial Engineering**
Institute of Industrial and Systems Engineers (IISE)
Email: iise@uprm.edu
ID: 103

Alpha Pi Mu (APM-UPRM)
Email: alphapimu@gmail.com
ID: 128

American Society for Quality (ASQ)
Email: asquality@gmail.com
ID: 5

Student Design Competition (SDC)
Email: sdcuprm@gmail.com
ID: 323

7. Computer Science and Engineering
PandaHat Cybersecurity Student Association (PANDAHAT-UPRM)
Email: pandahat@uprm.edu
ID: 398

BioMed Engineering Society (BMES)
Email: bmes@uprm.edu
ID: 422

IEEE UPRM Graduate Research & Academic Development in STEM (IEEE-UPRM GRADS)
Email: ieeeuprmgrads@gmail.com
ID: 423

RUMblebots
Email: rumblebots.crome@gmail.com
ID: 375

Evolving Space (ES)
Email: hello@evolvingspace.org
ID: 384

Pink Pandas Women in Cybersecurity
Email: pinkpandas@uprm.edu
ID: 413

**General/Multidisciplinary Engineering Organizations:**
Capítulo Estudiantil del Colegio de Ingenieros y Agrimensores de Puerto Rico (CECIA)
Email: desire.rivera2@upr.edu
ID: 400

**Comment by EdzelOrtiz** [comment]
Issue verified and completed!

@Adrianortiz-PR @AlexandraFuentes
