### ISSUE TITLE
{Initial Feature: CalendarPage} 【Sub-Issue】 Add icon and create event button to the ribbon

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#190]
Description: If you look at the current Ribbon, it is missing two things: the icon at the right and the create event button at the left. These two things need to be added. The icon can be downloaded from the [Figma design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?node-id=7-7&node-type=canvas&t=rztTLSxrnIQOvgUh-0).

**How it should look when finished**
![Image](https://github.com/user-attachments/assets/18087dba-6847-4d24-a767-e8741cbcab0e)

**How it looks right now**
![Image](https://github.com/user-attachments/assets/23f8d429-7420-4388-8b2f-7ceb4320fb0e)

**Acceptance Criteria:**
- The icon is present as shown in the design.
- The 'create event' button is present as shown in the design.
- Hovering the button turns the cursor into a pointing cursor (css property of cursor: pointer)

**Comment by vivianaramos6** [comment]
finished issue.  ![Image](https://github.com/user-attachments/assets/7d8489af-949b-4d17-a54c-33f78a170a25)

**Comment by vivianaramos6** [comment]
@Adrianortiz-PR @AlexandraFuentes
