### ISSUE TITLE
{Initial Feature: CalendarPage} 【Sub-Issue】 Fix bug in which calendar dates appear white instead of clack

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#204]
**Description:** The CalendarDay component has an element for the day, but it doesn't have a set color and it is the same color as the background. Similarly occurring with the arrows on the top right of the calendar. Fix this by setting its color to #333.

**Comment by SammyAlva04** [comment]
Issue completed @Adrianortiz-PR @AlexandraFuentes
