### ISSUE TITLE
{Initial Feature: Sign Up and Login} [Database Setup Sub Issue]  Database Setup and Interface

### ISSUE THREAD

**Issue by pierreg-vales** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#205]
Description: 

- Set up SQLite3 database and create a database interface file to handle interactions.
- Max assignees: 1

Subtasks:

- Create an SQLite3 database (or use a dummy database for now).

- Define a schema for storing user information (e.g., emails, hashed passwords).

- Create the interface.py file for database interaction functions (e.g., insert, retrieve).

- Use dummy data to test basic CRUD operations (Create, Read, Update, Delete).

Expected Outcome: 

- A basic SQLite3 database schema and interface ready for testing.

Completion Criteria for the Issue:

- SQLite3 database created (or dummy database used).

- Schema for user info (ID, Email, Hashed Password) implemented.

- CRUD operations in interface.py (Create, Read, Update, Delete) tested with dummy data.

**Comment by AlejandroClaudio** [comment]
Completed. 
@AlexandraFuentes @Adrianortiz-PR 

https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/commit/388b99eb062c55ef29114d448af5c43d659f635d
