### ISSUE TITLE
{Initial Feature: Sign up and Login} [Sub Issue] Oauth Application Registration

### ISSUE THREAD

**Issue by pierreg-vales** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#209]
Description: 

- To implement OAuth with Microsoft, the first step is to register our application with Microsoft Azure. This will allow us to obtain a client ID and client secret, necessary for the OAuth flow. We also need to configure the redirect URIs for both local and production environments.

Requirements:

1. Create a new application in Microsoft Azure Portal:

    Log in to the [Microsoft Azure Portal](https://portal.azure.com/).
    Navigate to Azure Active Directory > App registrations > New registration.
    Fill in the required fields such as application name, supported account types, and redirect URIs.

2. Generate Client ID and Client Secret:

    Once the application is registered, generate the Client ID (Application ID).
    Go to Certificates & Secrets and create a new client secret. Make sure to copy and store the secret securely, as it will only be displayed once.

3. Set Redirect URIs:

    Configure the redirect URIs for both the local development environment (e.g., http://localhost:3000/callback) and the production environment (e.g., https://your-production-domain.com/callback).
    Ensure that the URIs match the OAuth flow implementation on both frontend and backend.

Completion Criteria:

- Application is successfully registered in Microsoft Azure.
- Client ID and Client Secret are generated and securely stored.
- Redirect URIs for both local and production environments are set correctly.

**Comment by vivianaramos6** [comment]
@Adrianortiz-PR Completed
