### ISSUE TITLE
{Initial Feature: Calendar}【Sub-Issue】 Add Event Block

### ISSUE THREAD

**Issue by GabyMarr** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#219]
**Description:**
This issue is a continuation of the work discussed in Issue https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/issues/146, and involves implementing the block in which the event section will be displayed. The block should be visible at all times while in calendar screen. 

**Acceptance Criteria:**
The block is styled appropriately and integrates well with the website's overall design.
The block appears at all times during the viewing of the calendar page.
The functionality is tested across multiple devices and browsers to ensure responsiveness and performance.

**Design Reference:**
Figma File: [Eventero Design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?m=auto&t=WXZ03fz7DcJOl0ly-6)

**Comment by Adrianortiz-PR** [comment]
Add urgency and difficulty for approval

**Comment by GabyMarr** [comment]
@Adrianortiz-PR @AlexandraFuentes Done
