### ISSUE TITLE
change create event button color on hover

### ISSUE THREAD

**Issue by vivianaramos6** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#230]

**Comment by vivianaramos6** [comment]
finished @Adrianortiz-PR @AlexandraFuentes

**Comment by vivianaramos6** [comment]
![Image](https://github.com/user-attachments/assets/06474c2b-bcc0-4ea7-8aa6-3706ef0cacfc)


![Image](https://github.com/user-attachments/assets/427de06b-64f3-4791-8f3e-d4d3d499f6f8)

**Comment by Adrianortiz-PR** [comment]
Please add or mention in this comment thread a recommended difficulty and urgency for this task so you can get your points. I am thinking "Difficulty 2" and "Urgency 2" but I prefer when developers suggest since they worked on said task
@vivianaramos6
