### ISSUE TITLE
[Lecture Topic Task] Design and Implement Event Class with Core Scheduling Behaviors (create event class) 

### ISSUE THREAD

**Issue by MiguelGibo** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#246]
### Objective:
Design an Event class that captures the core concept of an event, encapsulating essential event information and key behaviors for scheduling and management.
### Description:
The Event class will represent scheduled events within the system, such as meetings or workshops. It should encapsulate all necessary attributes related to an event and implement methods for managing attendance, editing event details, and handling potential scheduling conflicts. This will support the functionality needed for users to create, organize, and participate in events effectively.
### Requirements:
Attributes:

- `event_id` (str): Unique identifier for each event. Research may be needed on how this can be generated automatically.
- `event_name` (str): Name of the event (e.g., "Coding Club Meeting").
- `room_id` (str): Identifier of the room where the event will take place.
- `organizer` (username): The user responsible for organizing the event, linked to a User instance.
- `attendees` (set): List of users who have RSVP'd or are attending the event.
- `date` (str): The day on which the event is scheduled in mm-dd-yyyy format (e.g. "02-27-1996" for February 2nd of 1996)
- `time` (int): Time slot for the event, using a 24-hour clock (e.g., 14:00 for 2 PM).
- `duration` (int): Duration of the event in hours or minutes (optional).
- `status` (str): Status of the event (e.g., "scheduled", "canceled", "in-progress", "completed").
- `capacity` (int): Maximum number of attendees the event can accommodate, based on room capacity.
- `description` (str): Optional description or additional notes about the event.
- `tags` (set): List of pre-approved tags for categorizing events (e.g., "workshop", "CIIC").

Behaviors:

- `add_attendee(username)`: Adds a user to the attendee's set, if the event has not reached its capacity, ensuring no duplicate RSVPs.
- `remove_attendee(user: User)`: Removes a user from the attendees list, updating their reservation status.
- `get_max_capacity()`: Returns the maximum capacity of the event.
- `get_current_capacity()`: Returns the remaining number of available spots (i.e., capacity - len(attendees)).
- `is_full()`: Returns True if the event has reached its maximum capacity, otherwise False.
- `cancel_event()`: Updates the event's status to "canceled" and notifies attendees of the cancellation.
- `edit_event(new_event_name: str, new_room_id: str, new_organizer: username, new_day: int, new_time: int, new_description: str, new_tags: list[str])`: Edits one or more attributes of an event and optionally notifies attendees of major changes.
- `check_conflict(other_event: Event)`: Checks for scheduling conflicts with another event, returning True if the two events overlap.

### Completion Criteria:

- The Event class is implemented with the required attributes and methods.
- Event instances can be created, updated, and canceled, with appropriate notifications sent to attendees.
- Scheduling conflicts can be identified between events sharing the same room and overlapping times.

**Comment by Ojani** [comment]
Loooks good, but use unix time to store the time

**Comment by AlexandraFuentes** [comment]
Looks great! :)
