### ISSUE TITLE
[Lecture Topic Task]  Analytics for Event Attendance and Resource Utilization

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#254]

**Comment by estefania-2817** [comment]
Objective: 
- Develop and integrate analytics tools into the app to track key performance metrics like event attendance and resource utilization

Description:
- This task focuses on integrating analytics into the app to measure how effectively the system increases resource utilization and event attendance
- The data collected will be used to generate reports and insights for administrators and event organizers

Implementation Plan:
1. Define key metrics to track booking rates and attendance
2. Implement data collection and storage for analytics
3. Create a dashboard for visualizing the metrics

Subtasks:
1. Define metrics and tracking points
2. Implement data storage for analytics
3. Design and implement a dashboard for real-time insights.

**Comment by estefania-2817** [comment]
[LTT_ Analytics for Event Attendance and Resource Utilization.pdf](https://github.com/user-attachments/files/17448632/LTT_.Analytics.for.Event.Attendance.and.Resource.Utilization.pdf)
