### ISSUE TITLE
[Lecture Topic Task] Setting up Node.js and Python Development Environments

### ISSUE THREAD

**Issue by LuisJCruz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#256]
**Objective:**
Guide developers in setting up the necessary environments for running both frontend and backend development servers, including Node.js and Python environments.

**Description:**
This task will document the steps required to clone the repository, install dependencies, and set up both Node.js and Python environments for development. It includes instructions for running the frontend and backend servers simultaneously.

**Implementation Plan:**
- Provide step-by-step instructions for setting up the Node.js environment and installing necessary modules.
- Document Python environment setup and package installation.
- Ensure smooth integration of the frontend and backend servers.

**Subtasks:**
- Write documentation for setting up Node.js and installing dependencies.
- Write documentation for setting up Python and Flask environment.
- Test the simultaneous running of frontend and backend servers.

DOCUMENT:
[Setting up Node.js and Python Development Environments.docx](https://github.com/user-attachments/files/17451475/Setting.up.Node.js.and.Python.Development.Environments.docx)

**Comment by Mannyrodd101** [comment]
[Setting.up.Node.js.and.Python.Development.Environments.docx](https://github.com/user-attachments/files/17525118/Setting.up.Node.js.and.Python.Development.Environments.docx)
