### ISSUE TITLE
[Lecture Topic Task] Logbook Creation for External GitHub Issue Tracking

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#269]
Assignees: Adrian Ortiz

Objective:
Develop a logbook system that records all GitHub issues closed outside the GitHub platform to ensure proper tracking and transparency across the team.

Description:
This task focuses on creating a logbook for tracking GitHub issues that are resolved or closed outside of the GitHub platform (e.g., via email, meetings, or other external communication tools). This logbook will provide a central record to maintain visibility into tasks that are completed outside GitHub, ensuring that no issue closure goes undocumented. This will help improve accountability and project oversight.

Implementation Plan:
Define a structure for the logbook that includes relevant details (e.g., issue ID, reason for external closure, closing person).

Create a template or file format to store this logbook within the project (e.g., CSV or JSON).

Implement a process for updating the logbook whenever an issue is closed externally.

Integrate the logbook with GitHub to cross-reference closed issues and ensure accuracy.

Subtasks:
1. Research and design the logbook schema to capture essential issue details.

2. Develop the logbook template and set up initial structure (file format and storage).

3. Implement a mechanism to cross-check closed issues on GitHub versus the logbook.

**Comment by Mannyrodd101** [comment]
Added Event Turner and Calendar Issues to Logbook.
