### ISSUE TITLE
{Documentation}【Sub-Issue】Implement the logbook structure, with real git commits.

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#291]
#### Objective:
To create a structured Excel sheet that serves as the logbook, capturing all necessary information for GitHub issues closed outside the GitHub platform.

#### Details:

1. *Define Columns and Headers:*  
   Create columns to capture key information for each closed issue:
   - *Issue ID*: Unique identifier for the GitHub issue.
   - *Issue Title*: Brief title or description of the issue.
   - *Closure Date*: Date when the issue was closed.
   - *Closing Person*: Name of the person responsible for closing the issue.
   - *Closure Reason*: Explanation for closing the issue outside GitHub (e.g., resolved in a meeting, addressed via email).
   - *Additional Notes*: Optional column for any other relevant details or context.

2. *Format and Styling:*
   - Set up column headers with bold formatting for easy readability.
   - Apply filters to each column header to enable quick searches and sorting.
   - Consider conditional formatting to highlight issues closed for specific reasons or by particular team members, enhancing quick data analysis.

3. *Storage and Access:*
   - Save the Excel file in a designated location within the project directory or shared drive to ensure team access.
   - Regularly back up the file, especially if updates are made frequently.

4. *Template Naming and Versioning:*
   - Name the file in a way that reflects its purpose and date (e.g., GitHub_External_Issue_Logbook_MM-YYYY.xlsx).
   - Implement version control if multiple team members will be updating the logbook, to avoid data loss and conflicts.

#### Next Steps:
- After creating the initial Excel template, review with the team to confirm the schema meets all needs.
- Establish a process for logging each entry systematically and make updates as needed.

**Comment by Mannyrodd101** [comment]
Added Event Turner and Calendar Issues to Logbook.
