### ISSUE TITLE
[Lecture Topic Task] TLA+ Formatting System Requirements

### ISSUE THREAD

**Issue by GabyMarr** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#295]
Continuation of issue #284. 

Broke down a set of system requirements for a university resource booking system into smaller, actionable tasks. Each requirement was translated into clear tasks that define specific functionalities and user interactions. This breakdown serves as a structured way to understand the components needed for the system, making it easier to implement and verify each feature. This process helps in organizing development efforts and ensuring that all necessary features are addressed systematically.

**Comment by GabyMarr** [comment]
@JeanSanchezFelix

**Comment by GabyMarr** [comment]
@Adrianortiz-PR @AlexandraFuentes Finished Issue

**Comment by AlexandraFuentes** [comment]
Give it a description
