### ISSUE TITLE
[Lecture Topic Task]  Agile Task Management and Planning Poker

### ISSUE THREAD

**Issue by ggonza28** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#298]
**Objective:**
Introduce agile practices into the project by utilizing Planning Poker for estimating development tasks and breaking them into manageable units.

**Description:**
This task focuses on using Planning Poker to estimate the size and complexity of each user story or task. This agile technique helps the team align on estimates and prioritize tasks based on their difficulty and importance.

**Implementation Plan:**
1. Organize Planning Poker sessions for the team.
2. Assign story points to tasks based on team consensus.
3. Prioritize tasks in the sprint based on estimates and project needs.

**Subtasks:**
1. Run Planning Poker sessions.
2. Assign and document story points for each task.
3. Organize tasks in the sprint backlog based on estimates.

**Comment by ggonza28** [comment]
Completed
Access the following google doc: https://docs.google.com/document/d/1e6IEpb4eDRDNo4Qxs3EMDn7ty4xwCXmuDwtpYTPjX-s/edit?usp=sharing
@EdzelOrtiz @AlexandraFuentes @Adrianortiz-PR

**Comment by EdzelOrtiz** [comment]
Verified. Completed Task
