### ISSUE TITLE
[Sub Issue] Display Location Names when hovering on Map

### ISSUE THREAD

**Issue by MiguelGibo** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#313]
**Description:**
Currently, when users want to identify which building is which they need to browse a 50+ legend. It goes without saying that that is very cumbersome and not very user-friendly. Implementing a hover feature that displays the name of the location would greatly improve user experience.

**Methods to implement:**
- Change map image
- add invisible buttons that will display text when hovering over an area.

**Comment by AlexandraFuentes** [comment]
I like this idea!
