### ISSUE TITLE
{Initial Feature: CalendarPage} 【Sub-Issue】 Modify CalendarDay component to enable time slots

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#317]
**Description:**
In the daily and weekly calendar views, the the events must be shown on the correct time slot on each day, but the CalendarDay component isn't capable of that.

**This issue is completed when**
- The CalendarDay component has a boolean property called **timed**
- When **timed** is true, the events in the calendar day will be placed in the correct time slot, provided by the start time and duration of the event

**Comment by Ojani** [comment]
@AlexandraFuentes @Adrianortiz-PR completed

**Comment by Ojani** [comment]
@AlexandraFuentes @Adrianortiz-PR y was it not closed :(

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣶⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⡿⢉⠀⠈⢿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠁⠀⠀⠀⠀⢿⣷⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡿⠀⠀⠀⠀⠀⠸⣿⡆⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⣿⣧⠀⢀⣀⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⢻⣿⡾⠿⠛⠿⣷⡄⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣼⣿⠀⠀⠀⠀⠀⠀⢸⣿⡄⠀⠀⠀⢹⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡾⠛⠉⠉⣿⠇⠀⠀⠀⠀⠀⠈⠛⠀⠀⠀⠀⢸⣿⡆
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣄⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⢻⣷⡄⠀⠀⠀⠀⢿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⠇⠀
⢀⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⠃⠀⢻⣷⠀⠀⠀⠀⣸⣿⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡟⠀⠀
⣾⣿⢿⣷⣄⠀⣀⣀⣠⣤⣤⡿⠇⠀⠀⠈⣿⡇⠀⢠⣾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡟⠀⠀⠀
⢸⣿⠀⠙⠻⠿⠛⠛⠉⠉⠁⣠⣴⣶⣶⣦⣿⣇⣴⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣴⠿⠋⠀⠀⠀⠀
⢸⣿⠀⣨⣵⣶⣶⣤⣀⢀⣾⣿⣿⣿⣿⠊⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣴⡾⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀
⠀⢻⣿⡏⢿⣿⣿⣿⣿⡟⣿⣿⣿⠟⢃⣾⠟⠁⠀⠀⠀⠀⠀⣀⣠⣴⡶⠟⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠘⣿⣧⠈⠻⢿⡿⣿⡇⠙⢿⣶⡶⠟⠁⠀⠀⢀⣠⣤⣶⠟⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠈⠻⢿⣶⣶⣶⣿⣷⠿⠟⠋⠀⢀⣤⣶⠾⠛⠉⢁⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣠⣶⠟⠋⠀⠀⠀⠀⠀⠀⠀⣿⣇⣀⣀⣠⠶⠛⠉⢻⡧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⣼⡟⠁⠀⠀⠀⠀⠀⠀⠀⡀⠀⠸⣿⣯⣍⣁⣀⣤⣴⠟⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣼⡟⠀⢀⣴⢿⣷⠀⠀⢀⣴⢷⣄⠀⢻⣯⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢰⣿⠃⢀⣼⡟⠈⣿⡇⠀⢸⡿⠈⣿⡄⠈⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠈⢿⣷⡾⠋⠀⢠⣿⠁⠀⣿⡇⠀⠘⣿⡄⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⣿⡇⠀⠀⠈⠛⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠸⣿⣄⣼⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

**Comment by AlexandraFuentes** [comment]
Closed 

              /| _ ╱|、  
             ( •̀ㅅ •́  )
       ＿ノ ヽ ノ＼＿ 
    /　`/ ⌒Ｙ⌒ Ｙ　 \
 ( 　(三ヽ人　 /　 　|
|　ﾉ⌒＼ ￣￣ヽ　 ノ
ヽ＿＿＿＞､＿＿／
          ｜( 王 ﾉ〈 
           /ﾐ`ー―彡\ 
          |╰          ╯|   
          |       /\       |
          |      /  \      |                    
          |    /     \     |
