### ISSUE TITLE
[Lecture Topic Task] Event Class Diagram

### ISSUE THREAD

**Issue by vivianaramos6** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#320]
Create a class diagram for Eventero to represent its structure, attributes, and methods. This diagram will document the class design for better clarity and future reference for developers

**Comment by AlexandraFuentes** [comment]
Please add description to close issue

**Comment by vivianaramos6** [comment]
<img width="1099" alt="Screenshot 2024-11-11 at 9 02 29 PM" src="https://github.com/user-attachments/assets/74674d27-9109-43bc-aebc-04a09af579bd">
@AlexandraFuentes @Adrianortiz-PR

**Comment by vivianaramos6** [comment]
wait

**Comment by vivianaramos6** [comment]
<img width="1013" alt="Screenshot 2024-11-11 at 9 03 58 PM" src="https://github.com/user-attachments/assets/d71ff9d4-f063-489f-8abf-2e6f16e7b10c">

**Comment by pierreg-vales** [comment]
@AlexandraFuentes @Adrianortiz-PR completed

**Comment by pierreg-vales** [comment]
faltan labels thats it
