### ISSUE TITLE
{Mini-Feature: Event Creation Pop-up}【Main-Issue】Design & Implementation

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#335]
**Overview:**  
We’re beginning the Event Creation component for Eventero! This feature will allow users to easily create events using a pop-up interface similar to Outlook's calendar event creation tool. With the homepage development completed, the homepage team (@JeanSanchezFelix's team) will now transition to this new feature.

**Objective:**  
The goal is to implement a user-friendly event creation tool that streamlines event setup. Users will be able to input key details such as event name, date, time, and location, while also setting up recurring events, choosing tags for categorization, and enabling features like RSVPs.

### Tasks Breakdown:

- [x] #356
   - Develop the base structure for a modal pop-up interface for event creation.
   - Ensure it is styled and positioned similarly to Outlook’s calendar pop-up tool.

- [x] #357
   - Add form fields for inputting:
      - Event Name
      - Event Date
      - Start and End Times
      - Location
   - Apply validation for each field (e.g., date and time formats, required fields).

- [x] #358
   - Implement dropdown or toggle options for recurring events (e.g., daily, weekly, monthly).
   - Ensure recurring settings are stored correctly for future reference.

- [x] #359
   - Add a section where users can select tags to categorize their events (e.g., Academic, Sports, Social).
   - Ensure multiple tags can be selected and saved.

- [x] #360
   - Add a toggle option to enable or disable RSVP for each event.
   - If enabled, display additional RSVP settings (e.g., max participants, custom RSVP message).

- [x] #361
   - Implement "Create Event" and "Cancel" buttons.
   - Ensure the “Create Event” button triggers event creation and stores input data.
   - The “Cancel” button should close the pop-up and clear any entered data.

- [x] #362
   - Display a confirmation message when an event is successfully created.
   - Show error messages for incomplete or incorrect input.

Feel free to contribute any thoughts or additional tasks in this thread. Let’s make this a smooth transition from the homepage to the event creation component!

**Example of Feature:**
Outlook Event Creation Pop-up as an example:  

![image](https://github.com/user-attachments/assets/bf525559-3ed6-401d-8889-a7cb02cdeddc)

_Originally posted by @AlexandraFuentes in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/240_</div>

**Comment by Mannyrodd101** [comment]
I resolved all of my issues
