### ISSUE TITLE
{Feature: Upcoming Events} 【Main-Issue】Search Bar

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#339]
**Description:**
This issue focuses on adding a **Search Bar** to the **Upcoming Events** page in Eventero. The search bar will allow users to quickly find events by typing keywords related to event names, dates, tags, or categories. This will improve navigation and make it easier for users to locate specific events within the platform.

---

#### **Requirements:**

- [x] #343
   - Design and position the search bar prominently at the top of the Upcoming Events page.
   - Ensure the search bar is styled consistently with the application’s design theme, using placeholders and clear input indicators.

- [x] #344
   - Enable keyword search functionality so users can find events based on title, description, tags, or other relevant keywords.
   - Use a dynamic filter that updates the event list as the user types.

- [x] #345
   - Allow users to filter events by specific dates or date ranges.
   - Incorporate a date picker into the search bar to simplify date selection.

- [x] #346
   - Allow users to filter events by tags or categories.
   - Ensure multiple tags or categories can be selected and applied simultaneously.

---

#### **Acceptance Criteria:**
- The search bar is positioned prominently on the Upcoming Events page and follows the Eventero design style.
- Users can search for events by typing keywords related to event titles, descriptions, tags, or categories.
- Filtering options for date, tags, and categories are fully functional.
- The event list dynamically updates based on search input, and a "No results found" message appears when appropriate.
- The search bar and filters are responsive across all device types and browsers.

---

#### **Design Reference:**
- Figma File: [Eventero Design – Upcoming Events](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?node-id=8-420&node-type=canvas)
  
![Image](https://github.com/user-attachments/assets/6574a153-eb53-42f3-ae85-09e67a4a546b)

#### **Documentation Reference:**
- Ensure your commits are documented: [Homepage doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7B93FC3995-80D4-42B5-BC60-4A9191E948C1%7D&file=Initial%20Feature%20-%20Homepage.docx&action=default&mobileredirect=true)
- Add relevant components to: [Component Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB4E17698-6B3A-431E-BE28-33D16902D251%7D&file=Component%20Reference.docx&action=default&mobileredirect=true)
- Verify feature integration: [Feature Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BBC785AF0-39F4-415F-A9E9-09297256B95E%7D&file=Feature%20Reference.docx&action=default&mobileredirect=true)

**Comment by marymarmaldonado** [comment]
@Adrianortiz-PR @AlexandraFuentes main task and subtasks done.
