### ISSUE TITLE
{Feature: Upcoming Events} 【Main-Issue】Events Dashboard

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#341]
**Overview:**
This issue focuses on building the **Events Dashboard** for the Upcoming Events feature. The dashboard will serve as a central hub where users can view, filter, and interact with upcoming campus events. It should be designed to display event information in a clean, user-friendly interface, similar to the reference image linked below.

**Objective:**
To implement an Events Dashboard that allows users to quickly access and explore upcoming events, including filtering by tags, dates, and categories.

#### **Tasks:**
- [x] #351
   - Establish the basic layout structure for the Events Dashboard, ensuring it is responsive across all screen sizes.
   - Set up sections for event details, filtering options, and any featured events.
  
- [x] #352
   - Design and integrate individual event cards to display key information like event name, date, time, location, and tags.
   - Make the event cards interactive, allowing users to click for more details.

- [x] #353
  - Implement a registration button on each event card.
  - Ensure users can RSVP with their email or other identifiers.
  - Display confirmation messages upon successful registration.
  - Track the number of RSVPs for each event and show available seats (if applicable).

 - [x] #354
   - Create a pop-up or modal that displays detailed event information when a user clicks on an event card **MORE** button.

- [x] #355
  - Allow users to switch between different views of the upcoming events (e.g., list view, or grid view).
  - Implement different event display modes for the dashboard (calendar view, timeline view, etc.).
  - Provide an easy toggle button to switch between views based on user preference.

---

#### **Acceptance Criteria:**
- The Events Dashboard layout is fully responsive and user-friendly.
- Event cards display accurate and updated event information.
- Filtering, sorting, and search functionalities are fully functional.
- User experience meets design expectations, with smooth navigation and interaction.

---

#### **Design Reference:**
- Figma File: [Eventero Design – Upcoming Events](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?node-id=8-420&node-type=canvas)

![Image](https://github.com/user-attachments/assets/998c0f34-72e0-4aa9-98f3-d997c3cc2613)

#### **Documentation Reference:**
- Ensure your commits are documented: [Homepage doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7B93FC3995-80D4-42B5-BC60-4A9191E948C1%7D&file=Initial%20Feature%20-%20Homepage.docx&action=default&mobileredirect=true)
- Add relevant components to: [Component Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB4E17698-6B3A-431E-BE28-33D16902D251%7D&file=Component%20Reference.docx&action=default&mobileredirect=true)
- Verify feature integration: [Feature Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BBC785AF0-39F4-415F-A9E9-09297256B95E%7D&file=Feature%20Reference.docx&action=default&mobileredirect=true)

**Comment by LuisJCruz** [comment]
Documentation: [https://sistemaupr-my.sharepoint.com/:w:/g/personal/ojani_figueroa_upr_edu/ERtF5Byo0YxGqZySaLUK-94BT-XFvqATmQ_TJIfY4VX9VQ?e=OfhkR5](url)

**Comment by LuisJCruz** [comment]
@JeanSanchezFelix
