### ISSUE TITLE
{Feature: Upcoming Events}【Sub-Issue】Implement Event Details Form Fields

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#357]
**Description:**
This is a sub-task for the **Event Creation** feature as outlined in #335. The task focuses on developing specific components for an intuitive, user-friendly event creation interface. The feature will allow users to seamlessly input event details such as name, date, time, location, and additional settings like recurring events, categorization tags, and RSVP options.

Each sub-task will contribute to refining different aspects of the event creation flow, ensuring a smooth and efficient experience for the user. Please ensure all work follows the provided design and documentation references to maintain consistency with the overall project goals.

#### **Design Reference:**
- Outlook Event Creation Pop-up: ![image](https://github.com/user-attachments/assets/bf525559-3ed6-401d-8889-a7cb02cdeddc)

#### **Documentation Reference:**
- Ensure all commits follow the documentation guidelines as outlined in the [Homepage doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7B93FC3995-80D4-42B5-BC60-4A9191E948C1%7D&file=Initial%20Feature%20-%20Homepage.docx&action=default&mobileredirect=true).
- Update relevant components in the [Component Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB4E17698-6B3A-431E-BE28-33D16902D251%7D&file=Component%20Reference.docx&action=default&mobileredirect=true).
- Verify feature integration as specified in the [Feature Reference doc](https://sistemaupr-my.sharepoint.com/:w:/r/personal/ojani_figueroa_upr_edu/_layouts/15/Doc.aspx?sourcedoc=%7BBC785AF0-39F4-415F-A9E9-09297256B95E%7D&file=Feature%20Reference.docx&action=default&mobileredirect=true).

**Comment by AlexisSantiago21** [comment]
@Adrianortiz-PR @AlexandraFuentes done, can you close this issue, please?
