### ISSUE TITLE
Update Associations Dictionaries for Universal Associations

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#373]
Description: Update the universal association tags to include additional tags based on newly identified associations. This task ensures that the universal tags remain comprehensive and reflective of all available organizations within the university. The updated tags will allow users to select from a broader and more accurate list of universal associations.

Requisites:
Stage 1:
	•	Review the current list of universal association tags and identify gaps or missing associations.
	•	Incorporate newly identified associations into the universal tags list to ensure inclusivity.
	•	Ensure that the updated tags are seamlessly integrated into the front-end interface, allowing users to select them without impacting existing functionality.
	•	Use the link provided by the research, UPRM Organizations, to verify and add all official universal associations.

Prerequisites:
	•	Existing universal association tags integrated into the application.
	•	Resources:
	•	Figma Design for the Tags Organization
	•	Repository

Roles and Responsibilities:
	•	Managers: Oversee the process, ensuring that the updated tags are accurate and aligned with university organizations.
	•	Team Leaders: Facilitate communication between Managers and Developers, provide clarification on updated tags, and assist with implementation if needed.
	•	Developers: Implement the updated universal tags, ensuring smooth integration into the front-end and back-end systems.

**Comment by cseba11** [comment]
@Adrianortiz-PR @AlexandraFuentes Issue #373 completed.
