### ISSUE TITLE
Update Associations Dictionaries for Unique Associations

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#374]
Description: Update the unique association tags to include additional associations specific to different majors. This task ensures that each major has a comprehensive list of unique associations available to its students. The updated tags will enhance user experience by providing more tailored association options for students based on their selected major.

Requisites:
Stage 1:
	•	Review the current list of unique association tags for each major and identify gaps or missing associations.
	•	Add newly identified associations specific to each major, ensuring the tags are accurate and relevant.
	•	Ensure seamless integration of the updated tags into the front-end, dynamically displaying them based on the user’s selected faculty and major.
	•	Use the link provided by the research, UPRM Organizations, to verify and add all official unique associations for each major.

Prerequisites:
	•	Existing unique association tags integrated into the application.
	•	Resources:
	•	Figma Design for the Tags Organization
	•	Repository

Roles and Responsibilities:
	•	Managers: Oversee the process, ensuring that the updated unique tags align with the associations relevant to each major.
	•	Team Leaders: Facilitate communication between Managers and Developers, provide clarification on unique tags for majors, and assist with implementation if needed.
	•	Developers: Implement the updated unique tags for each major, ensuring they appear correctly in the front-end and are integrated with the back-end systems for selection tracking.

**Comment by ggonza28** [comment]
Completed. 
Currently working on #373 to merge branch.
@Adrianortiz-PR  @AlexandraFuentes
