### ISSUE TITLE
Refine UI Components with Figma Design

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#375]
Description: Refine the existing UI components to align with the Figma design, ensuring consistency with the project’s visual identity. This task involves updating the already implemented page to match the detailed styling, spacing, and layout outlined in the Figma design. The updated UI will provide a more polished and cohesive user experience.

Requisites:
Stage 1:
	•	Review the current implementation of the page and identify discrepancies between the implemented design and the Figma mockup.
	•	Update styling elements such as colors, fonts, spacing, button designs, and overall layout to match the Figma design precisely.
	•	Test the updated UI for responsiveness, ensuring compatibility across devices and screen sizes.
	•	Maintain functionality and ensure no features are disrupted during the design update.

Prerequisites:
	•	Access to the Figma design file for reference.
	•	Existing implementation of the page with basic functionality in place.
	•	Resources:
	•	Figma Design for the Tags Organization
	•	Repository

Roles and Responsibilities:
	•	Managers: Oversee the refinement process, ensuring the updated UI aligns with project goals and user expectations.
	•	Team Leaders: Coordinate between the design team and developers to clarify design requirements and resolve any conflicts.
	•	Developers: Implement the updated design, ensuring accurate translation from Figma to the web page, while preserving functionality and responsiveness.

Acceptance Criteria:
	•	Full alignment of UI components with the Figma design, including styling, layout, and responsiveness.
	•	All existing functionality preserved after the design update.
	•	Visual testing completed across multiple devices to confirm compatibility.
	•	Confirmation from stakeholders or the design team that the refined UI meets expectations.

**Comment by kevin-d-lopez** [comment]
Completed with userProfilePage branch @AlexandraFuentes @Adrianortiz-PR
