### ISSUE TITLE
Association Tag Requirements

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#376]
Description: Implement a requirement that enforces users to select a minimum number of association tags before they can proceed. The tags must be diverse, including both universal associations and those specific to their selected major. This ensures that users engage with the selection process and tailor their association preferences effectively.

Requisites:
Stage 1:
	•	Define a minimum number of required tags users must select (e.g., one universal association and one major-specific association).
	•	Add validation to ensure the minimum selection criteria are met before proceeding.
	•	Provide feedback to users if the minimum selection is not met (e.g., “Please select at least one universal association and one association related to your major”).
	•	Ensure the validation logic works dynamically, adjusting based on the associations available to the user.

Prerequisites:
	•	Existing association tags, both universal and major-specific, implemented in the application.
	•	Resources:
	•	Figma Design for the Tags Organization
	•	Repository

Roles and Responsibilities:
	•	Managers: Ensure that the requirement aligns with project objectives and user expectations.
	•	Team Leaders: Coordinate with developers to clarify requirements and provide oversight during implementation.
	•	Developers: Implement the validation logic and ensure proper integration with the front-end and back-end, allowing the system to enforce the tag selection requirement dynamically.

Acceptance Criteria:
	•	Validation logic ensures users select the minimum required tags (e.g., at least one universal and one major-specific).
	•	Clear feedback is provided to users when the requirement is not met.
	•	No user can proceed to the next step without fulfilling the tag selection criteria.
	•	Proper testing ensures validation works seamlessly across different scenarios (e.g., varying numbers of tags available).
	•	The functionality is fully integrated and visually aligned with the Figma design.

**Comment by kevin-d-lopez** [comment]
Issue finished in the userProfilePage branch. @AlexandraFuentes  @Adrianortiz-PR
