### ISSUE TITLE
[Main Issue] Develop User Profile Webpage

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#377]
Description: Develop a new profile webpage that displays the user’s selected tags, along with their profile information, including a profile picture. This page serves as a centralized view of the user’s preferences and personal details, providing an intuitive and aesthetically pleasing interface for managing their profile and tags.

Requisites:
Stage 1:
	•	Profile Section:
	•	Display the user’s profile picture, name, and basic details (e.g., email, bio).
	•	Allow users to upload or update their profile picture directly on the page.
	•	Tags Section:
	•	List the user’s selected tags, categorized by type (e.g., universal associations, major-specific associations, etc.).
	•	Provide options to edit or update the selected tags if needed.
	•	Design and Responsiveness:
	•	Ensure the page design aligns with the Figma mockup, focusing on layout, colors, and spacing.
	•	Make the webpage responsive, providing a seamless experience across desktop and mobile devices.

Prerequisites:
	•	Access to the user’s profile data and selected tags from the backend.
	•	Resources:
	•	Figma Design for the Profile Page
	•	Repository

Roles and Responsibilities:
	•	Managers: Oversee the page design and implementation, ensuring it aligns with project goals and user needs.
	•	Team Leaders: Coordinate between developers and designers to clarify requirements and resolve any discrepancies.
	•	Developers:
	•	Implement the profile and tags display using data from the backend.
	•	Add functionality for updating the profile picture and tags.
	•	Ensure the page is fully responsive and visually aligned with the Figma design.

Acceptance Criteria:
	•	The profile section accurately displays the user’s profile picture, name, and other personal details.
	•	The tags section lists all selected tags, categorized and displayed neatly, with options for editing.
	•	Users can upload or update their profile picture without errors.
	•	The page design matches the Figma mockup, including responsiveness for different devices.
	•	Full integration with the backend, ensuring that data is fetched and updated correctly.

**Comment by Kiarancole** [comment]
completed in userProfilePage branch. @AlexandraFuentes @Adrianortiz-PR
