### ISSUE TITLE
[Sub Issue] Webpage Skeleton

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#378]
Description: Develop the skeleton for the profile webpage, which will serve as the foundation for displaying the user’s profile and selected tags. This task focuses on creating the basic structure of the page, including sections for the profile picture, user details, and tag categories, without adding full functionality or dynamic content.

Requisites:
Stage 1:
	•	Basic Structure:
	•	Create a section for the user’s profile picture and basic details.
	•	Add placeholders for displaying selected tags, categorized into universal and major-specific sections.
	•	Include a section for editing/updating profile information and tags.
	•	Styling and Layout:
	•	Apply basic CSS for layout and spacing to ensure the structure is visually clear.
	•	Align the skeleton design with the Figma mockup, focusing on overall layout and positioning.
	•	Responsiveness:
	•	Ensure the structure is responsive, adapting to both desktop and mobile screens.

Prerequisites:
	•	Figma mockup for the profile webpage layout.
	•	Resources:
	•	Figma Design for the Profile Page
	•	Repository

Roles and Responsibilities:
	•	Managers: Review the skeleton design and verify that it aligns with project goals and user requirements.
	•	Team Leaders: Assist developers in clarifying layout requirements and coordinating with the design team.
	•	Developers:
	•	Build the basic HTML and CSS structure for the page.
	•	Ensure placeholders and sections are properly positioned according to the mockup.
	•	Test the skeleton for responsiveness and adjust as needed.

Acceptance Criteria:
	•	The profile webpage skeleton includes sections for the profile picture, user details, and tags.
	•	Placeholder elements are clearly visible and correctly positioned.
	•	The structure is visually consistent with the Figma mockup.
	•	Responsiveness is implemented, ensuring the layout adapts smoothly to various screen sizes.
	•	The skeleton serves as a foundation for adding dynamic content and functionality in later tasks.

**Comment by Kiarancole** [comment]
Finished in userProfilePage branch. @AlexandraFuentes @Adrianortiz-PR
