### ISSUE TITLE
[Sub Issue] Add User Profile 

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#380]
Description: Add functionality to display the user’s profile information on the profile webpage. This task involves fetching and displaying key details, such as the user’s name, email, and other personal information. This ensures that the profile page provides a clear and personalized overview of the user.

Requisites:
Stage 1:
	•	Frontend:
	•	Create placeholders for user information fields, such as name, email, and bio.
	•	Design the layout to visually align with the Figma mockup.
	•	Backend:
	•	Create an endpoint to fetch user profile information.
	•	Ensure that user data is securely stored and retrieved efficiently.
	•	Integration:
	•	Connect the frontend placeholders with the backend to dynamically display the user’s information.
	•	Implement an option for users to update their profile information.

Prerequisites:
	•	Existing skeleton of the profile webpage with sections for displaying profile information.
	•	Resources:
	•	Figma Design for the Profile Page
	•	Repository

Roles and Responsibilities:
	•	Managers: Ensure that the displayed user profile information aligns with project goals and privacy policies.
	•	Team Leaders: Facilitate communication between backend and frontend developers to streamline data integration.
	•	Developers:
	•	Implement the API endpoint for fetching and updating user profile information.
	•	Connect the frontend and backend to display dynamic user data.
	•	Test the system to ensure data is retrieved and updated without errors.

Acceptance Criteria:
	•	The profile webpage displays the user’s name, email, and other personal information accurately.
	•	User data is fetched securely from the backend and displayed dynamically on the frontend.
	•	The layout and styling match the Figma mockup.
	•	Users can update their profile information, and changes are reflected correctly.
	•	Placeholder text or design elements display properly for incomplete or missing data.

**Comment by kevin-d-lopez** [comment]
Issue completed in the userProfilePage branch. @AlexandraFuentes @Adrianortiz-PR
