### ISSUE TITLE
[Sub Issue] Add the Tags page block with the Users Tags

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#381]
Description: Add functionality to display the tags the user selected on the tags page within the profile webpage. This task involves retrieving the user’s chosen tags and categorizing them for display in a dedicated section on the profile page. It ensures continuity between the tags page and the profile page, providing a cohesive user experience.

Requisites:
Stage 1:
	•	Frontend:
	•	Create a section on the profile page to display the user’s chosen tags.
	•	Use blocks or categories (e.g., universal tags, major-specific tags) to organize and visually represent the selected tags.
	•	Align the styling of the tags display with the Figma design for consistency.
	•	Backend:
	•	Create an endpoint to fetch the user’s selected tags, categorized as universal and major-specific.
	•	Ensure the tags data is retrieved based on the authenticated user.
	•	Integration:
	•	Fetch the tags data from the backend and dynamically populate the tags section on the profile page.
	•	Allow for real-time updates if the user makes changes to their tags on the tags page.

Prerequisites:
	•	Functionality for selecting tags on the tags page must already be implemented.
	•	Resources:
	•	Figma Design for the Tags and Profile Pages
	•	Repository

Roles and Responsibilities:
	•	Managers: Ensure that the tags displayed on the profile page are accurately retrieved and visually consistent with the tags page.
	•	Team Leaders: Coordinate between developers to confirm seamless integration of tags from the tags page to the profile page.
	•	Developers:
	•	Implement the backend logic to fetch the user’s selected tags.
	•	Design the frontend display for the tags on the profile page.
	•	Test the integration to ensure that tags are correctly fetched and displayed, even after updates on the tags page.

Acceptance Criteria:
	•	The profile webpage displays the tags selected by the user, categorized and organized as on the tags page.
	•	The data fetch process ensures the correct tags are displayed for the authenticated user.
	•	The tags section visually aligns with the Figma design and remains responsive across devices.
	•	Real-time updates to tags on the tags page are reflected on the profile page without errors.
	•	Placeholder text or design elements display properly if no tags have been selected by the user.

**Comment by Kiarancole** [comment]
Finished on userProfilePage branch, working on #382 before merging. @Adrianortiz-PR @AlexandraFuentes
