### ISSUE TITLE
[Lecture Topic Task] Sprint Planning for Campus Resource App

### ISSUE THREAD

**Issue by Kiarancole** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#388]
Objective:

Implement sprint planning to organize and prioritize tasks for the development of the Campus Resource and Event Management App.

Description:

This task involves conducting sprint planning meetings where the team moves prioritized items from the product backlog to the sprint backlog. Each team member will choose tasks to work on for the sprint duration, ensuring alignment with the project timeline and goals.

Implementation Plan:

1. Organize a sprint planning meeting with the team.
2. Review and prioritize backlog items (features, bugs, improvements).
3. Assign tasks to team members and set sprint goals.

Subtasks:

1. Hold sprint planning meetings bi-weekly.
2. Move selected tasks from the product backlog to the sprint backlog.
3. Set measurable goals for each sprint.

**Comment by estefania-2817** [comment]
[Lecture Topic_ Sprint Planning for Campus Resource App.pdf](https://github.com/user-attachments/files/17908708/Lecture.Topic_.Sprint.Planning.for.Campus.Resource.App.pdf)

**Comment by estefania-2817** [comment]
completed @AlexandraFuentes @Adrianortiz-PR
