### ISSUE TITLE
[Lecture Topic Task] Creating Dummy Data for Testing Tags and Profile Pages

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#392]
Assignees: Edzel Ortiz, Gabriel Gonzalez

Objective:
Generate realistic dummy data to test the functionality and layout of the tags page and profile page. The dummy data will simulate user interactions, including selected tags and profile information, ensuring the features perform as expected under various scenarios.

Description:
This task involves creating a dataset that mimics real-world inputs for both the tags page and profile page. The dummy data will include user profile information, selected universal and major-specific tags, and other relevant details. By using this data, developers can validate that both pages render and handle information correctly, ensuring a smooth user experience. The dataset will also help identify potential bugs or inconsistencies during development.

Implementation Plan:
Define Dummy Data Requirements:
Profile information: Include fields like, name, email, profile picture, and bio.
Tags Data: Generate universal and major-specific tags for multiple users, ensuring diversity in selections.
Create a Dataset:
Develop a JSON or database file with predefined dummy users and their corresponding tags.
Ensure the dataset reflects various combinations of tags, including edge cases like no tags selected or all categories selected.
Integrate Dummy Data for Testing:
Feed the dummy data into the backend to simulate API responses for the tags page and profile page.
Use the data to test dynamic rendering, responsiveness, and interactions on both pages.

Validate Results:
Confirm that the tags page correctly displays and allows interaction with the dummy tags.
Verify the profile page renders the profile information and selected tags accurately.

Subtasks:
Define dummy data structure and fields (e.g., profile information, tags).
Create a sample dataset
Load dummy data into the backend or mock API responses for testing.
Test tags page functionality, including tag selection and display.
Test profile page functionality, including rendering of profile info and selected tags.

**Comment by EdzelOrtiz** [comment]
https://docs.google.com/document/d/1Ap0jexZwqSu76VB64rBo8HYv8YoWsy-VxRbNzLGbOjQ/edit?usp=sharing

Added the documentation for this Lecture Topic Task

Can close issue @AlexandraFuentes @Adrianortiz-PR

**Comment by ggonza28** [comment]
Completed

Use following link for reference. 
https://docs.google.com/document/d/1Ap0jexZwqSu76VB64rBo8HYv8YoWsy-VxRbNzLGbOjQ/edit?usp=sharing @EdzelOrtiz @Adrianortiz-PR @AlexandraFuentes
