### ISSUE TITLE
[Sub Issue] {Documentation Event Tuner} Association Tag Requirement

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#396]
Description:
Define the purpose and usage of association tags within the feature. Provide examples to illustrate how the tags are categorized and used, ensuring clarity for both developers and stakeholders.

Responsibilities:
	•	Explain the purpose of association tags in the system and how they enhance user experience.
	•	Describe the categories of tags (e.g., universal, major-specific) and their differences.
	•	Provide usage examples for each category, including scenarios and functionality.
	•	Ensure the documentation includes sufficient detail for future reference and maintenance.

Acceptance Criteria:
	•	The documentation includes a clear explanation of association tags and their categories.
	•	Examples are provided for universal and major-specific tags.
	•	The purpose and usage of tags are described in a way that is easily understood by all team members.
	•	The documentation aligns with the overall structure and guidelines of the team’s documentation.

**Comment by ggonza28** [comment]
Completed.
Reference the following doc, section titled "Association tag requirements documentation"
https://docs.google.com/document/d/1Ap0jexZwqSu76VB64rBo8HYv8YoWsy-VxRbNzLGbOjQ/edit?usp=sharing
@EdzelOrtiz @AlexandraFuentes @Adrianortiz-PR
