### ISSUE TITLE
[Sub Issue] {Documentation Event Tuner} Update Associations Dictionaries

### ISSUE THREAD

**Issue by EdzelOrtiz** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#397]
Description:
Document the structure and maintenance of the associations dictionaries used for categorizing tags. Provide guidelines for updating the dictionaries, ensuring consistency and ease of use.

Responsibilities:
	•	Describe the purpose of the associations dictionaries and how they are structured.
	•	Include examples of universal and major-specific associations in dictionary format.
	•	Provide detailed guidelines for adding, updating, or removing entries in the dictionaries.
	•	Explain testing requirements for dictionary updates to ensure proper integration with the feature.

Acceptance Criteria:
	•	The documentation includes a detailed explanation of the dictionaries’ structure and purpose.
	•	Examples of universal and major-specific associations are provided in a clear format.
	•	Guidelines for updates and testing are included and easy to follow.
	•	The documentation supports consistent and accurate maintenance of the dictionaries over time.

**Comment by ggonza28** [comment]
Completed.
Reference the following document, section titled "Associations dictionaries update documentation".
https://docs.google.com/document/d/1Ap0jexZwqSu76VB64rBo8HYv8YoWsy-VxRbNzLGbOjQ/edit?usp=sharing
@EdzelOrtiz @Adrianortiz-PR @AlexandraFuentes
