### ISSUE TITLE
[Lecture Topic Task]  Removing Unused Branches to follow Clean Arquitecture

### ISSUE THREAD

**Issue by vivianaramos6** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#402]
### **Description**:

This task focuses on removing unused branches from the repository to maintain a clean and organized codebase in line with clean architecture principles. By eliminating outdated or irrelevant branches, the team ensures that the repository remains easy to navigate and free of clutter. This task aligns with best practices for repository management and supports efficient development workflows.

---

**Objective**:
The objective is to review all branches in the repository, identify unused or obsolete ones, and remove them safely without affecting active development. This contributes to maintaining a well-structured repository that adheres to clean architecture principles.

---

**Steps**:
1. **Review Repository**:
   - List all branches currently in the repository.
   - Identify branches that are outdated, merged, or no longer relevant.
   
2. **Confirm with Team**:
   - Communicate with team members to confirm whether any branches flagged for deletion are still in use or required.
   
3. **Backup Important Changes**:
   - For branches with incomplete or abandoned work, create a backup or document key changes before deletion.

4. **Remove Unused Branches**:
   - Use `git branch -d <branch-name>` for local branch deletions and `git push origin --delete <branch-name>` for remote branches.

5. **Document Changes**:
   - Keep a log of the removed branches for reference and transparency.
   - Update the team on repository cleanup during the next stand-up or sprint meeting.

---

**Expected Outcome**:
A clean and organized repository with only active branches, improving team efficiency and aligning the project structure with clean architecture standards.

**Comment by pierreg-vales** [comment]
Completed @Adrianortiz-PR @AlexandraFuentes

**Comment by AlexandraFuentes** [comment]
Updated Description and closed
