### ISSUE TITLE
[Lecture Topic Task] Ojani

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#421]

**Comment by Ojani** [comment]
The scrum meeting lasted around 30 minutes. The TL;DR/Synopsis of the meeting can be found in [this link](https://drive.google.com/file/d/1Se5wOzmeqxZBSKPUiQpjWL-EAg5ayXwP/view?usp=sharing)
