### ISSUE TITLE
OAuth Athentification Research 

### ISSUE THREAD

**Issue by pierreg-vales** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#49]
**Description:**

- User sign up and log in deals with passwords and doing so directly can be unsafe and prone to vulnerabilities. To prevent this, there could be a way to avoid working with passwords directly using OAuth authentification. OAuth, or open authorization, is a widely adopted authorization framework that allows you to consent to an application interacting with another on your behalf without having to reveal your password. 

**Requirements:** 

1. Features:

- Research what kind of features it has and what can be used for its implementation. 
- Verify if it still can be possible to limit the sign up and log in to UPR Accounts. 

2. Difficulty: 

- Research the difficulty it has to be implemented time and complexity wise. The purpose of OAuth is to facilitate the log in and sign up process. 

**Acceptance Criteria:**

1. A report is delivered detailing whether OAuth is beneficial or not backed up with references. Details the features, difficulty, and pros and cons. 
2. The manager approves of the report.

**Comment by AngelUPR** [comment]
OAuth research has been completed and is currently being discussed for implementation
