### ISSUE TITLE
{Initial Feature: User Log-In} Research and learning Svelte and Python Confirmation

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#53]
#### **Description:**

To prepare for future development using Python Flask (backend) and Svelte (frontend), the team needs to familiarize themselves with the basic concepts, structure, and setup of these technologies.

---

#### **Tasks:**

1. **Python Flask (Backend):**
   - Learn how to set up a basic Flask application.
   - Understand the routing system in Flask.
   - Learn how to handle requests and responses.
   - Explore how to integrate APIs or create endpoints using Flask.
   - Set up a basic project using Flask and test some routes.

2. **Svelte (Frontend):**
   - Learn the fundamentals of Svelte (e.g., components, reactivity, stores).
   - Understand how to set up a basic Svelte project.
   - Get familiar with Svelte's syntax and how it differs from React.
   - Implement basic data binding and event handling in Svelte components.

---

#### **Resources:**
- Flask Documentation: https://flask.palletsprojects.com/en/2.0.x/
- Svelte Documentation: https://svelte.dev/docs

---

#### **Outcome:**
Team members should have a basic understanding of Flask and Svelte and be able to set up simple applications using both technologies. This knowledge will be foundational for future project work.

**Comment by GabyMarr** [comment]
I finished Svelte and Python Flask Learning.

**Comment by arianrodz21** [comment]
I also finished Svelte and Python Flask Learning.

**Comment by Ingrid1089** [comment]
I finished learning Svelte and Python Flask.

**Comment by AngelUPR** [comment]
Every team member has completed the suggested Svelte and Flask tutorial and can now begin coding
