### ISSUE TITLE
{Initial Feature: Homepage} Svelte Learning Confirmation

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#55]
**Description:**

This issue is intended to confirm that the relevant team members have completed their learning of Svelte and are ready to apply their knowledge to the project. The following tasks should be completed:

1. **Complete Svelte Learning Resources:**
   - Ensure that all assigned team members have completed the provided Svelte learning materials or courses.
   - This includes any official documentation, tutorials, or courses specified.

2. **Demonstrate Understanding:**
   - Each team member should demonstrate their understanding of Svelte by:
     - Sharing a brief summary or key takeaways from their learning.
     - Providing examples of Svelte concepts they are now comfortable with (e.g., reactive statements, stores, components).

 3. **Confirmation:**
   - Once the above tasks are completed, confirm that all team members are proficient with Svelte and are ready to contribute effectively to the project.

4. **Notice:**
   - This task is only for the members of the Homepage feature implementation, them being: @marymarmaldonado, @Mannyrodd101, @KennethSepu1,  #@AlexisSantiago21, @LuisJCruz 

---
#### **Resources:**
- Svelte Documentation: https://svelte.dev/docs

**Comment by SaucyRexy** [comment]
You mentioned “Ensure that all assigned team members have completed the provided Svelte learning materials or courses”, have you made a list of the provided materials\courses or are you all learning from different sources? I think it would be a good idea to include said materials/courses for future developers that end up working on features involving Svelte, so it’s easier for them to find the appropriate resources.

**Comment by JeanSanchezFelix** [comment]
> You mentioned “Ensure that all assigned team members have completed the provided Svelte learning materials or courses”, have you made a list of the provided materials\courses or are you all learning from different sources? I think it would be a good idea to include said materials/courses for future developers that end up working on features involving Svelte, so it’s easier for them to find the appropriate resources.


In the discussion #22 for choosing the framework, @Ojani provided the resource for learning the framework on the [official tutorial](https://learn.svelte.dev/tutorial/welcome-to-svelte). Additionally, in our first meeting, whose recording is available [here](https://sistemaupr-my.sharepoint.com/:v:/r/personal/alexandra_fuentes2_upr_edu/Documents/Recordings/First%20Eventero%20Weekly%20Scrum-20240906_010023-Meeting%20Recording.mp4?csf=1&web=1&e=dAfIv3&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D), we once again talked about where you can find the official Svelte tutorial. It was both mentioned verbally and written in the chat. Nonetheless I will modify this task to meet your requirements and include the link for the Svelte tutorial.

**Comment by LuisJCruz** [comment]
Im all up to date with the required Svelte material needed for the project.

**Comment by marymarmaldonado** [comment]
I am also up to date with the Svelte tutorial. 

Svelte is a framework that is relatively easy to understand. I completed the tutorial and read the documentation, therefore believe I am proficient and ready to contribute to the project feature.

**Comment by SaucyRexy** [comment]
> > You mentioned “Ensure that all assigned team members have completed the provided Svelte learning materials or courses”, have you made a list of the provided materials\courses or are you all learning from different sources? I think it would be a good idea to include said materials/courses for future developers that end up working on features involving Svelte, so it’s easier for them to find the appropriate resources.
> 
> In the discussion #22 for choosing the framework, @Ojani provided the resource for learning the framework on the [official tutorial](https://learn.svelte.dev/tutorial/welcome-to-svelte). Additionally, in our first meeting, whose recording is available [here](https://sistemaupr-my.sharepoint.com/:v:/r/personal/alexandra_fuentes2_upr_edu/Documents/Recordings/First%20Eventero%20Weekly%20Scrum-20240906_010023-Meeting%20Recording.mp4?csf=1&web=1&e=dAfIv3&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D), we once again talked about where you can find the official Svelte tutorial. It was both mentioned verbally, written in the MS Teams chat and in the WhatsApp Homepage community chat. Nonetheless I will modify this task to meet your requirements and include the link for the Svelte tutorial.
> 
> It is also important to note that this issue is specifically for my Homepage team not for everyone in Eventero.

Thank you for linking the appropriate information. Regardless if it was discussed somewhere else, since this is the main issue, it's important to have it documented here or simply state here where it was discussed and provide the appropriate link to said destination. Even though this issue is specifically made for the Homepage team, it doesn't take away the fact that we might have to come back to it sometime in the future due to bugs, updates, and any other number of issues. As developers might be assigned to different features then, it's important to have the documentation included so that anybody that wasn't part of the original team, even those part of the same team, can revist the resources and have them at their disposal easily. Thank you for including the link to the Svelte tutorial, as well as the different locations in which record of said resources can be found.

**Comment by AlexisSantiago21** [comment]
I have completed the Svelte learning resources and have a good understanding of the key concepts. I am comfortable with concepts such as reactive declarations and the use of stores.

**Comment by KennethSepu1** [comment]
I'm up to date with learning HTML , CSS and JavaScript. I also learned how to use Svelte

**Comment by Mannyrodd101** [comment]
I have completed all of the Svelte learning resources.
