### ISSUE TITLE
Create Documentation for Tags in Eventero's Personalized Profile Questionnaire

### ISSUE THREAD

**Issue by AlexandraFuentes** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#57]
**Description**  
We need to create a comprehensive documentation for the tag-based interest selection in the *Eventero* campus event app. This documentation will outline the different categories of tags available to users during the personalized profile setup, along with the specific tags under each category. The purpose of this feature is to allow users to customize their experience by selecting tags that align with their campus life and event interests.

**Tasks**
1. **Introduction Section**:  
   - Provide an overview of the *Tag-Based Interest Selection* feature.
   - Explain the **Interactive Questionnaire** where users select tags by swiping or clicking, similar to Pinterest-style pin selection.
  
2. **Tag Categories Section**:  
   - List the categories of tags available for selection:
     - **Academic Interests**
     - **Campus Activities**
     - **Cultural Events**
     - **Career Development**
     - **Social and Recreational**
     - **Resource Utilization**
  
3. **Detailed Tag Listings**:  
   - For each category, provide a detailed list of relevant tags:
     - **Academic Interests**:
       - Study Groups (Math, Science, Engineering, Humanities)
       - Workshops and Seminars
     - **Campus Activities**:
       - Clubs and Organizations
       - Sports and Recreation
     - **Cultural Events**:
       - Performances (Theater, Music, Dance)
       - Festivals and Celebrations
     - **Career Development**:
       - Networking Events
       - Internship Opportunities
     - **Social and Recreational**:
       - Social Events (Parties, Mixers)
       - Hobbies and Interests (Gaming, Crafting)
     - **Resource Utilization**:
       - Study Spaces
       - Tech Facilities

**Expected Outcome**  
- A structured and detailed documentation page that outlines all tag categories and specific tags to be used in the personalized profile questionnaire for event recommendations.

**Additional Notes**  
- Ensure that the documentation is clear and user-friendly, with appropriate formatting for easy understanding.
- The documentation will be used by the development team to implement the tagging system in the app’s user profile flow.

**Comment by AlexandraFuentes** [comment]
https://docs.google.com/document/d/1eRrK3Kl1VFdRiOfS0B9S9_nvu9R-ZG1TKkz7eBl8RcM/edit?usp=sharing

**Comment by AngelUPR** [comment]
Document has been completed and all tags have been created at the moment of writing this
