### ISSUE TITLE
{Initial Feature: Calendar} Svelte Learning Confirmation

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#62]
**Description:**

Since this team is mostly frontend, I will be requiring the team members to learn the frontend framework of choice for this project, Svelte. To ensure this is done, team members should comply by the following instructions.

1. **Complete Official Svelte Tutorial**
   - Complete part 1 and part 2 of the Svelte tutorial found [here](). Part 3 and 4 are not necessary.
   - Other resources can be used to learn more if you so please, but please complete the tutorial so that everyone has at least the same base understanding.
   - I recommend using Chrome so that the Svelte tutorial editor is less prone to being buggy, but if changes made aren't being reflected on the tutorial, refresh the page (copy your code beforehand because this will reset the editor).
   -  Once a team member finishes the Svelte tutorial, they should leave a comment confirming so. Do **NOT** rush through the tutorial, a little extra time investment now will save many more hours of being stuck later.

2. **Cloning Repository**
   - Each team member is expected to clone the repository and follow the setup instruction in the README.
   - Once a team member is able to view the web page in their browser, they should leave a comment confirming that they were able to do so.

3. **When is This Task Completed:**
   - Once each member confirms they have completed the Svelte tutorial and that they have successfully cloned the repository, the task is completed and this issue will be closed.

---
#### **Resources:**
- Svelte Documentation: https://svelte.dev/docs

---
### PS
I recommend raising the difficulty for these initial feature tasks because of the time it takes to learn a new framework and setting up the repository. I will wait for the response of @SaucyRexy and/or @AngelUPR to see if they think it is appropriate and to what difficulty it should be raised.

**Comment by AngelUPR** [comment]
We have agreed to raise the difficulty from a 2/5 to a 3/5

**Comment by vivianaramos6** [comment]
Completed

**Comment by cseba11** [comment]
Completed

**Comment by ggonza28** [comment]
Finalized

**Comment by AngelUPR** [comment]
Every team member has completed the recommended Svelte tutorial
