### ISSUE TITLE
Tags Organization

### ISSUE THREAD

**Issue by SaucyRexy** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#81]
### Discussed in https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **EdzelOrtiz** September 13, 2024</sup>
Description:

Develop a tag-based system for university users to select their faculties, majors, and official organizations. This system will guide users through three stages: selecting a faculty, choosing a major within that faculty, and selecting related university organizations. The tags will help organize users' academic and extracurricular profiles based on their choices, streamlining their access to relevant information.

Requisites:

Stage 1
- Create a page where users can select one of the four University Faculties.
Steps:
- 1. Gather a list of the four University Faculties.
- 2. Create a tile-based selection system displaying the faculties.
- 3. Save the user's selection to filter content for the next step

Stage 2
- Based on the user's selection, display all the majors associated with that faculty.
Steps:
- 1. Retrieve the list of majors under each faculty from the first link provided.
- 2. Display the majors as selectable tags.
- 3. Ensure the system accurately reflects the relationship between the selected faculty and its associated majors.

Stage 3:
- Display official University organizations affiliated with the user's selected faculty and any extracurricular organizations.
Steps:
- 1. use the second link to gather the list of organizaions.
- 2. Filter the organizations based on the faculty selected in Stage 1.
- 3. Include extracurricular organizations that are available to all users.
- 4. Display the organizations in an easy to select format.

Prerequisites:
- Resources:
- Link 1: Faculties and Majors: [UPRM Faculties & Majors](https://www.uprm.edu/asuntosacademicos/oferta-academica-2/)
- Link 2: Official University Organizations: [UPRM Organizations](https://www.uprm.edu/cms/index.php?a=file&fid=20375)
- Access to the content management system (CMS) where the tags will be implemented.
- Database or tag system to store the selections.

- Permissions:
- Ensure that access to the necessary CMS and university databases is granted.
- Dependencies:
- Accurate and up-to-date data from the faculties, majors, and organizations.
- Potential support from web developers or IT for CMS integration.

Potential Risks or Challenges
- Data Inconsistencies: The data from the provided links may be outdated or incomplete. Regular updates and verification are needed.
- Mitigation: Cross-check the provided data with official university sources.
- User Experience: The process must be intuitive to avoid user confusion.
- Mitigation: Run user testing to identify any pain points or areas for improvement.

Roles and Responsibilities:
- Managers: Oversees the process, ensuring the feature works as it is intended to do so.
- Team Leaders: Maintain effective communication between Managers and Developers, may also help with implementation.
- Developers: Responsible for implementing the front-end and back-end aspects of the selection system.</div>

**Comment by EdzelOrtiz** [comment]
Issue Completed
