### ISSUE TITLE
{Initial Feature: User Sign-Up} Svelte Learning Confirmation

### ISSUE THREAD

**Issue by pierreg-vales** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#82]
Description:

Since this team is mostly frontend, I will be requiring the team members to learn the frontend framework of choice for this project, Svelte. To ensure this is done, team members should comply by the following instructions.

    Complete Official Svelte Tutorial
        Complete part 1 and part 2 of the Svelte tutorial found [here](https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/issues/62). Part 3 and 4 are not necessary.
        Other resources can be used to learn more if you so please, but please complete the tutorial so that everyone has at least the same base understanding.
        I recommend using Chrome so that the Svelte tutorial editor is less prone to being buggy, but if changes made aren't being reflected on the tutorial, refresh the page (copy your code beforehand because this will reset the editor).
        Once a team member finishes the Svelte tutorial, they should leave a comment confirming so. Do NOT rush through the tutorial, a little extra time investment now will save many more hours of being stuck later.

When is This Task Completed:

    Once each member confirms they have completed the Svelte tutorial.
 

Resources:

    Svelte Documentation: https://svelte.dev/docs

**Comment by AlejandroClaudio** [comment]
I have finished the svelte tutorial of part 1 and part 2.

**Comment by WilsonMorales8** [comment]
I have finished learning part 1 and 2 of the Svelt video tutorials.

**Comment by AngelUPR** [comment]
All members have confirmed the Svelte tutorial according
