### ISSUE TITLE
{Initial Feature: User Sign-Up} Cloning Repository Confirmation

### ISSUE THREAD

**Issue by pierreg-vales** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#83]
Description:

Each team member has to clone the repository to be able to create commits and make changes to the project.

Requierements:

1. Each team member is expected to clone the repository and follow the setup instruction in the README.
2. Once a team member is able to view the web page in their browser, they should leave a comment confirming that they were able to do so.

Confirmation Criteria:

Each member succesfully clones the repository.

**Comment by MiguelGibo** [comment]
I've finished cloning the repo

**Comment by AlejandroClaudio** [comment]
I cloned the repository and successfully ran the web page.
