### ISSUE TITLE
{Initial Feature: User Log-In} Cloning Repo confirmation 

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#84]
Each team member has to clone the repository to be able to create commits and make changes to the project.

Requirements:

Each team member is expected to clone the repository and follow the setup instructions in the README.
Once a team member is able to view the web page in their browser, they should leave a comment confirming that they were able to do so.
Confirmation Criteria:

Each member successfully clones the repository.

**Comment by AngelUPR** [comment]
Every member, confirmed by the team leader, has cloned the repository to create commits and make changes
