### ISSUE TITLE
{Initial Feature: User Log-In} Cloning Assistance for Team Members

### ISSUE THREAD

**Issue by Adrianortiz-PR** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#85]
Description: This issue is created to assist team members with cloning the repository and setting it up locally. Please refer to the README file for detailed setup instructions.

If any issues arise during the process, Adrian is available to help. Feel free to leave a comment on this issue if you encounter any problems or need further assistance.

**Comment by AngelUPR** [comment]
Cloning repository and setup has been completed by all team members
